import React from 'react';
import { CompleteCV } from '@shared/types';
import generateProfessionalHTML from './ProfessionalTemplateHTML.ts';

interface ProfessionalTemplateHTMLProps {
  data: CompleteCV;
}

/**
 * Professional template - a classic, formal CV design using pure HTML (no CSS)
 * This component uses dangerouslySetInnerHTML to render the HTML generated by generateProfessionalHTML
 */
const ProfessionalTemplateHTML: React.FC<ProfessionalTemplateHTMLProps> = ({ data }) => {
  // Generate the HTML string
  const htmlContent = generateProfessionalHTML(data);
  
  return (
    <div 
      className="cv-template-wrapper"
      dangerouslySetInnerHTML={{ __html: htmlContent }} 
    />
  );
};

export default ProfessionalTemplateHTML;